### PR TITLE
Update skill_data_AS.js

### PR DESCRIPTION
**Pull request by Yuuram**
Corrected confusing descriptions.

Foes -> Targets
Downs foes hit X seconds -> Knockdown target for X seconds

### CODE REVIEW

**Comment by dakaringer** [comment]
I was kinda indecisive whether to use foes, enemies, or targets... but I guess targets would work a bit better yes.

As for Knockdown, I will change it to "Knock down" instead to make it more consistent with "Knock up" and "Knock back"

**Comment by Yuuram** [comment]
Hiya Darkringer,
Just found your simulator and figured out I would help out to clean up the descriptions alittle!

First of all thank you for your quick action response but the translation is still a little off. * I am only starting from assassin skill tree because it is my class and I will be able to give a better translated version of the descriptions.
Example. 
A) Knocks down targets hit for 3 sec

vs

A.1) Knockdown target(s) for X sec
I don't think there's such a word "knocks down" and also knock down target and HIT for 3 second might be confusing to new players, they might assume knock down target and then hit target for 3 seconds.
Love your work and I wouldn't insist what should be changed or not but hopefully you could give my suggestion/change a thought!
Cheers,Yuuram
Date: Mon, 19 Jan 2015 18:03:10 -0800

**Comment by Yuuram** [comment]
I missed out the part about you saying knock up / knock down.
You can easily change knock up into "Knock target into the air" simple and less confusing. Knockup can mean alot of things and only add to the confusion when the description is "Knocks-up targets hit" I think the HIT is over used in quite a few of the description. It's quite self explanatory for most of the skills without the 'hit' part.
I can refine more of the skill descriptions for you if you do not mind.

Date: Mon, 19 Jan 2015 18:03:10 -0800

**Comment by dakaringer** [comment]
Hmm.. you do have a point..
How about this
Knocks down -> Knock down
Knocks back -> Knock back
Knocks up -> Knock ... into the air
targets hit -> targets

I'm also thinking about reverting back "targets" to "foes" to differentiate "foe targeted by the player" and "other foes".
target(s) -> foe(s)

Your feedback has been most helpful!

**Comment by dakaringer** [comment]
Not all abilities require a target

**Pull request merged**
